services:
  nginx:
    image: nginx:latest
    container_name: hello-world-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx-config:/etc/nginx/conf.d:ro
